name: Run Dashboard

on:
  push:
    branches: [ "master" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: [self-hosted, linux, ARM64]
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        export PATH=$PATH:/home/pi/.local/bin
        pipenv sync
    - name: Run Dashboard
      run: |
        pipenv run python main.py
